remote_theme: pages-themes/minimal@v0.2.0
title: Bailey Wellen Osweiler
subtitle: Computational Health Services Researcher
description: "Bailey Wellen Osweiler — computational and data sciences researcher focused on addiction health services and public policy."
logo: /newheadshot.jpeg

defaults:
  - scope:
      path: ""
    values:
      layout: default
